<html>
<head>
</head>
<body>
<form id="paymentForm" action="<?php echo $block->getMerchantLandingPageUrl(); ?>" method="get">
<input type="hidden" id="merchantTxId" name="merchantTxId" value=""/>
</form>
<div id="cashierDiv" style="max-width: 600px; margin: 0 auto;"></div>
<script type="text/javascript" src="<?php echo $block->getJsUrl(); ?>"></script>
<script type="text/javascript">
new payfabricpayments({<?php
foreach ($block->getFormFields() as $field => $value) {
    echo $field.':"'.$value.'",';
}
?>successCallback:handleResult,failureCallback:handleResult});
function handleResult(data) {console.log(data);
    if(data.RespStatus == "Approved"){
        document.getElementById("merchantTxId").value = data.TrxKey;;
        document.getElementById("paymentForm").submit();
    }else{
        setTimeout(function(){location.reload();}, 3000);
    }
}
 </script>
</body>
</html>
