<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var PayFabric\Payment\Block\Customer\Wallets $block */
$wallets = $block->getWallets();
?>
<?php if (count($wallets) !== 0): ?>
    <div class="table-wrapper my-credit-cards">
        <table class="data table table-credit-cards" id="my-orders-table">
            <caption class="table-caption"><?= /* @noEscape */ __('PayFabric Wallet') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col card-number"><?= /* @noEscape */ __('Tender') ?></th>
                <th scope="col" class="col card-type"><?= /* @noEscape */ __('Card Type') ?></th>
                <th scope="col" class="col expire"><?= /* @noEscape */ __('Exp. Date') ?></th>
                <th scope="col" class="col card-number"><?= /* @noEscape */ __('Account #') ?></th>
                <th scope="col" class="col card-number"><?= /* @noEscape */ __('First Name') ?></th>
                <th scope="col" class="col card-number"><?= /* @noEscape */ __('Last Name') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($wallets as $field => $wallet) {
            ?>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('Tender')) ?>" class="col card-tender">
                    <?= $wallet->Tender ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Card Type')) ?>" class="col card-type">
                    <?= $block->escapeHtml($wallet->CardName ) ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Exp. Date')) ?>" class="col card-expire">
                    <?= $block->escapeHtml($wallet->ExpDate) ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Account')) ?>" class="col card-number">
                    <?= $block->escapeHtml($wallet->Account) ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('FirstName')) ?>" class="col card-firstname">
                    <?= $block->escapeHtml($wallet->CardHolder->FirstName) ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('LastName')) ?>" class="col card-lastname">
                    <?= $block->escapeHtml($wallet->CardHolder->LastName) ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                    <form
                            class="form"
                            action="<?= $block->escapeUrl($block->getUrl('payfabric/wallet/deleteaction')) ?>"
                            method="post"
                    >
                        <?= $block->getBlockHtml('formkey') ?>
                        <input
                                name="<?= /* @noEscape */ 'id' ?>"
                                value="<?= /* @noEscape */ $wallet->ID ?>"
                                type="hidden"/>
                        <button type="submit"
                                class="action delete"
                                data-mage-init='{
                                "Magento_Vault/js/customer_account/deleteWidget":{
                                    "type": "popup",
                                    "modalClass": "my-credit-cards-popup",
                                    "toggleEvent": "click",
                                    "title": "<?= $block->escapeHtml(__('Delete')) ?>",
                                    "content": "Are you sure you want to delete this wallet: <?=
                                /* @noEscape */ $wallet->Account
                                ?>?"
                                }
                            }'>
                            <span><?= $block->escapeHtml(__('Delete')) ?></span>
                        </button>
                    </form>
                </td>
            </tr>
            <?php
            }
            ?>
            </tbody>
        </table>
    </div>

<?php else: ?>
    <div class="message info empty"><span><?= /* @noEscape */ __('You have no wallet.') ?></span></div>
<?php endif ?>
