<html>
<head>
</head>
<body>
<form id="paymentForm" action="<?php echo $block->getMerchantLandingPageUrl(); ?>" method=<?php echo $block->escapeHtml($block->getFormMethod()) ?>>
<input type="hidden" id="TrxKey" name="TrxKey" value=""/>
</form>
<div id="cashierDiv" style="max-width: 600px; margin: 0 auto;"></div>
<script type="text/javascript" src="<?php echo $block->getJsUrl(); ?>"></script>
<?php
$fields = $block->getFormFields();
if(!empty($fields['status']) && 'error' == $fields['status']) {
    echo "<script type='text/javascript'>window.alert('".$fields['message']."'); window.location = '".$block->getUrl('checkout/cart')."'</script>";
}else{
?>
<script type="text/javascript">
new payfabricpayments({<?php
foreach ($fields as $field => $value) {
    echo $field.':"'.$value.'",';
}
?>successCallback:handleResult,failureCallback:handleResult});
function handleResult(data) {
    if(data.RespStatus == "Approved"){
        document.getElementById("TrxKey").value = data.TrxKey;;
        document.getElementById("paymentForm").submit();
    }else{
        setTimeout(function(){location.reload();}, 3000);
    }
}
 </script>
<?php } ?>
</body>
</html>
