<html>
<head>
</head>
<body>
    <?php
        $fields = $block->getFormFields();
        if(!empty($fields['status']) && 'error' == $fields['status']) {
            echo "<script type='text/javascript'>window.alert('".$fields['message']."'); window.location = '".$block->getUrl('checkout/cart')."'</script>";
        }else{
    ?>
    <form id="payfabric_payment_form" method="<?php echo $block->escapeHtml($block->getFormMethod()) ?>" action="<?php echo $block->escapeHtml($block->getCashierUrl()) ?>" name="payfabric_payment_form">

        <?php
        foreach ($fields as $field => $value) {
            echo '<input type="hidden" name="'.
                $block->escapeHtml(htmlspecialchars($field, ENT_COMPAT | ENT_HTML401, 'UTF-8')).
                '" value="'.$block->escapeHtml(htmlspecialchars($value, ENT_COMPAT | ENT_HTML401, 'UTF-8')).'" />';
        }
        ?>
    </form>
    <script type="text/javascript">
         document.getElementById('payfabric_payment_form').submit();
    </script>
    <?php } ?>
</body>
</html>
